### ISSUE TITLE
Allow users to pass in numpy array or file handler in save method

### ISSUE THREAD

**Issue by AbyAbraham21** [simvue-io/python-api#15]
The simvue.save method should allow users to pass in a numpy array or a file handler. This check should be done in the method and either the np array is pickled and stored or saved. User should not have to do this.

**Comment by AbyAbraham21** [comment]
In addition to np array, users should also be allowed to pass in a matplotlib object

**Comment by kzscisoft** [comment]
This feature has been implemented for quite a while now 🙂
