### ISSUE TITLE
Fix Folder Tag Updating

### ISSUE THREAD

**Issue by kzscisoft** [simvue-io/python-api#248]
When using `set_folder_details` to update the tags of an existing folder the tags are not added on the server. This was discovered when addressing #105.

```python
client = Client()
client.set_folder_details('/path/to/folder', tags=["test_tags"])
```

May or may not have something to do with the fact currently the server only accepts strings not lists.

**Comment by alahiff** [comment]
> May or may not have something to do with the fact currently the server only accepts strings not lists.

For folder tags? That's not true - if I try to use a string, rather than a list, I get a 422:
```
{"detail":[{"loc":["body","tags"],"msg":"value is not a valid list","type":"type_error.list"}]}
```
so it definitely wants a list rather than a string.

The API works correctly as far as I can tell, e.g.:
```
curl -i -X PUT -H "Content-Type: application/json" \
        -H "Authorization: Bearer <token>" \
        --data '{"id": "KsUDKULkbc3ZX5oL4DaDGM", "tags": ["tag1", "tag2", "a1"]}' \
        https://dev02.simvue.io/api/folders
```

**Comment by kzscisoft** [comment]
@alahiff my mistake, thanks for looking into this, must be on the client side

**Comment by kzscisoft** [comment]
Seems to work albeit with bugs on API side (see #479)
