### ISSUE TITLE
CLI Metric Dispatch

### ISSUE THREAD

**Issue by kzscisoft** [simvue-io/python-api#271]
An idea for a quick to use Simvue CLI. Request a run ID:

```sh
$ simvue --token <SIMVUE-TOKEN> --url <SIMVUE-URL> init
k32lANrwqoi234jjaS3la
```

```sh
$ simvue --token <SIMVUE-TOKEN> --url <SIMVUE-URL> add-metrics k32lANrwqoi234jjaS3la "{'a': 10}"
```

**Comment by alahiff** [comment]
Having a CLI could be very useful!

Of course, should get the token from `simvue.ini` or env variables by default, but having arguments as well would be good (e.g. for testing as a different user, with a different server etc).

**Comment by kzscisoft** [comment]
Closing as moved to https://github.com/simvue-io/simvue-cli
