### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by AbyAbraham21** [simvue-io/python-api#3]
Add logging module and store any errors to the log, so exceptions are not raised at the client level

**Comment by alahiff** [comment]
Related to this it would be good to tidy up return codes, or if they should be there at all? (I'm never sure what the best practice is in Python, i.e. return codes vs exceptions).

**Comment by kzscisoft** [comment]
Logging is performed and there is a way to suppress exceptions so the messages are logged as opposed to cause termination
