### ISSUE TITLE
Transient network issues (e.g. retrieving abort status) shouldn't cause the client to die

### ISSUE THREAD

**Issue by alahiff** [simvue-io/python-api#458]
Vignesh got this error last night:
```
RuntimeError: Exception retrieving abort status: HTTPSConnectionPool(host='test.simvue.io', port=443): Max retries exceeded with url: /api/runs/dmAnTMyk8ofWhjQXNa9yEe/abort (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14dc8b14ed40>, 'Connection to test.simvue.io timed out. (connect timeout=10)'))
```
The server was accessible from Europe, the US, Asia and Australia throughout last night, and all requests to this route were in the millisecond range, so it wasn't a server issue.

It would be good if the client didn't die so quickly in the event of potentially transient issues.

**Comment by kzscisoft** [comment]
Closed in `v1.0.6`
